import 'package:flutter/material.dart';

class AppLanguage {
  static final ValueNotifier<String> currentLocale = ValueNotifier<String>('hu');

  static void setLanguage(String langCode) {
    currentLocale.value = langCode;
  }

  static final Map<String, Map<String, String>> _dict = {
    'hu': {
      'slogan': 'Fedezd fel Ciprust: Szállások, Ízek & Túrák',
      'search_region_hint': 'Válassz ciprusi régiót vagy várost...',
      'cat_accommodations': 'Apartmanok\n& Ingatlanok',
      'cat_experiences': 'Élmények\n& Túrák',
      'cat_gastronomy': 'Gasztronómia\n& Bárok',
      'cat_transfer': 'Reptéri\ntranszfer ✈️',
      'nearby_search_bar': 'Autóbérlés, patikák, boltok a közeledben...',
      'nearby_services_title': 'Közeli szolgáltatások térképen 🗺️',
      'choose_region_title': 'Válassz ciprusi úti célt 🏝️',
      'view_details': 'Megtekintés',
      'featured_badge': 'KIEMELT',
      'all_regions': 'Összes régió (Egész Ciprus)',

      'auth_login_title': 'CYVESTA Bejelentkezés',
      'auth_register_title': 'Új Fiók Létrehozása',
      'auth_desc': 'Mentsd el kedvenceidet és kezeld a foglalásaidat!',
      'auth_email_hint': 'E-mail cím',
      'auth_password_hint': 'Jelszó',
      'auth_name_hint': 'Teljes név',
      'auth_business_name_hint': 'Vállalkozás / Szállásadó Neve',
      'auth_tax_hint': 'Hivatalos cégadatok / Adószám',
      'auth_address_hint': 'Cím (Település, utca, házszám)',
      'auth_phone_hint': 'Telefonszám',
      'auth_forgot_pass': 'Elfelejtetted a jelszavadat?',
      'auth_login_btn': 'Bejelentkezés',
      'auth_register_btn': 'Regisztráció',
      'auth_or_social': 'Vagy folytasd a következőkkel:',
      'auth_google': 'Folytatás Google fiókkal',
      'auth_apple': 'Folytatás Apple fiókkal',
      'auth_facebook': 'Folytatás Facebook fiókkal',
      'auth_switch_to_register': 'Nincs még fiókod? Regisztrálj itt!',
      'auth_switch_to_login': 'Már van fiókod? Jelentkezz be!',
      'auth_logout_btn': 'Kijelentkezés',
      'auth_logged_in_as': 'Bejelentkezve mint:',
      'auth_btn_main': 'Bejelentkezés & Fiók 👤',
      'lang_title': 'Nyelv kiválasztása / Language',

      'terms_acceptance': 'Elfogadom az ÁSZF-et és a ciprusi GDPR adatvédelmi irányelveket.',
      'role_guest': 'Vendég',
      'role_free': 'INGYENES',
      'role_annual': 'Éves Partner ⭐',
      'role_annual_price': '€240 (€20/hó)',
      'role_half_year': 'Féléves Partner',
      'role_half_year_price': '€180 (6 hó)',

      'btn_stripe_annual': 'Stripe Fizetés & Regisztráció (€240/év)',
      'btn_stripe_half': 'Stripe Fizetés & Regisztráció (€180/6 hó)',
      'btn_guest_reg': 'Ingyenes Vendég Regisztráció',

      'transfer_title': 'Reptéri Transzfer ✈️🚖',
      'transfer_header_title': 'Megbízható Ciprusi Transzferek',
      'transfer_header_desc': 'Larnaca (LCA) és Paphos (PFO) repülőterekről fix áras transzferek.',
      'transfer_step1_title': '1. Transzfer Iránya',
      'transfer_dir_to_stay': 'Reptér ➔ Szállás',
      'transfer_dir_to_airport': 'Szállás ➔ Reptér',
      'transfer_step2_title': '2. Járat & Úti Cél Részletei',
      'transfer_dest_hint': 'Szállás / Város neve',
      'transfer_flight_num': 'Járatszám (pl. W6 2451)',
      'transfer_phone_hint': 'Telefonszámod / WhatsApp *',
      'transfer_submit_btn': 'Transzfer Árajánlat Kérése (WhatsApp) 🚖',
      'transfer_fill_required': 'Kérjük töltsd ki a célállomást és az elérhetőségedet!',

      // Ingatlan típus választó kulcsok
      'choose_property_type': 'Válassz ingatlan típust 🏠',
      'rent_apartments': 'Apartmanok & Kiadó lakások',
      'rent_apartments_desc': 'Hosszú vagy rövid távú bérlemények Cipruson.',
      'sale_properties': 'Eladó Ingatlanok & Villák',
      'sale_properties_desc': 'Közvetlen eladó tengerparti ingatlanok és befektetések.',
    },

    'en': {
      'slogan': 'Discover Cyprus: Stays, Tastes & Tours',
      'search_region_hint': 'Select a Cyprus region or city...',
      'cat_accommodations': 'Apartments\n& Real Estate',
      'cat_experiences': 'Experiences\n& Tours',
      'cat_gastronomy': 'Dining\n& Bars',
      'cat_transfer': 'Airport\nTransfer ✈️',
      'nearby_search_bar': 'Car rentals, pharmacies, stores near you...',
      'nearby_services_title': 'Nearby Services on Map 🗺️',
      'choose_region_title': 'Choose Destination in Cyprus 🏝️',
      'view_details': 'View Details',
      'featured_badge': 'FEATURED',
      'all_regions': 'All Regions (Whole Cyprus)',

      'auth_login_title': 'CYVESTA Sign In',
      'auth_register_title': 'Create New Account',
      'auth_desc': 'Save your favorites and manage bookings!',
      'auth_email_hint': 'Email Address',
      'auth_password_hint': 'Password',
      'auth_name_hint': 'Full Name',
      'auth_business_name_hint': 'Business / Host Name',
      'auth_tax_hint': 'Company Details / Tax Number',
      'auth_address_hint': 'Address (City, Street, House No.)',
      'auth_phone_hint': 'Phone Number',
      'auth_forgot_pass': 'Forgot your password?',
      'auth_login_btn': 'Sign In',
      'auth_register_btn': 'Register',
      'auth_or_social': 'Or continue with:',
      'auth_google': 'Continue with Google',
      'auth_apple': 'Continue with Apple',
      'auth_facebook': 'Continue with Facebook',
      'auth_switch_to_register': "Don't have an account? Sign up here!",
      'auth_switch_to_login': 'Already have an account? Sign in!',
      'auth_logout_btn': 'Log Out',
      'auth_logged_in_as': 'Logged in as:',
      'auth_btn_main': 'Sign In & Account 👤',
      'lang_title': 'Select Language',

      'terms_acceptance': 'I accept the Terms & Conditions and Cyprus GDPR privacy policies.',
      'role_guest': 'Guest',
      'role_free': 'FREE',
      'role_annual': 'Annual Partner ⭐',
      'role_annual_price': '€240 (€20/mo)',
      'role_half_year': '6-Month Partner',
      'role_half_year_price': '€180 (6 mo)',

      'btn_stripe_annual': 'Stripe Payment & Registration (€240/year)',
      'btn_stripe_half': 'Stripe Payment & Registration (€180/6 months)',
      'btn_guest_reg': 'Free Guest Registration',

      'transfer_title': 'Airport Transfer ✈️🚖',
      'transfer_header_title': 'Reliable Cyprus Airport Transfers',
      'transfer_header_desc': 'Fixed-price transfers from Larnaca & Paphos airports.',
      'transfer_step1_title': '1. Transfer Direction',
      'transfer_dir_to_stay': 'Airport ➔ Stay',
      'transfer_dir_to_airport': 'Stay ➔ Airport',
      'transfer_step2_title': '2. Flight & Destination Details',
      'transfer_dest_hint': 'Stay / City name',
      'transfer_flight_num': 'Flight Number (e.g. W6 2451)',
      'transfer_phone_hint': 'Phone Number / WhatsApp Contact *',
      'transfer_submit_btn': 'Request Transfer Quote (WhatsApp) 🚖',
      'transfer_fill_required': 'Please enter destination and contact details!',

      'choose_property_type': 'Choose Property Type 🏠',
      'rent_apartments': 'Apartments & Rentals',
      'rent_apartments_desc': 'Long or short term rentals in Cyprus.',
      'sale_properties': 'Properties for Sale & Villas',
      'sale_properties_desc': 'Direct beachfront properties and investments.',
    },

    'el': {
      'slogan': 'Ανακαλύψτε την Κύπρο: Διαμονή, Γεύσεις & Εκδρομές',
      'search_region_hint': 'Επιλέξτε περιοχή ή πόλη...',
      'cat_accommodations': 'Διαμερίσματα\n& Ακίνητα',
      'cat_experiences': 'Εμπειρίες\n& Εκδρομές',
      'cat_gastronomy': 'Γαστρονομία\n& Μπαρ',
      'cat_transfer': 'Μεταφορά\nΑεροδρομίου ✈️',
      'nearby_search_bar': 'Ενοικίαση αυτοκινήτων, φαρμακεία, καταστήματα κοντά σας...',
      'nearby_services_title': 'Υπηρεσίες στον χάρτη 🗺️',
      'choose_region_title': 'Επιλέξτε προορισμό στην Κύπρο 🏝️',
      'view_details': 'Προβολή',
      'featured_badge': 'ΠΡΟΤΕΙΝΟΜΕΝo',
      'all_regions': 'Όλες οι περιοχές',

      'auth_login_title': 'Σύνδεση CYVESTA',
      'auth_register_title': 'Δημιουργία Λογαριασμού',
      'auth_desc': 'Αποθηκεύστε τα αγαπημένα σας και διαχειριστείτε τις κρατήσεις σας!',
      'auth_email_hint': 'Διεύθυνση Email',
      'auth_password_hint': 'Κωδικός πρόσβασης',
      'auth_name_hint': 'Ονοματεπώνυμο',
      'auth_business_name_hint': 'Όνομα Επιχείρησης / Οικοδεσπότη',
      'auth_tax_hint': 'Στοιχεία Εταιρείας / ΑΦΜ',
      'auth_address_hint': 'Διεύθυνση (Πόλη, Οδός, Αριθμός)',
      'auth_phone_hint': 'Αριθμός Τηλεφώνου',
      'auth_forgot_pass': 'Ξεχάσατε τον κωδικό σας;',
      'auth_login_btn': 'Σύνδεση',
      'auth_register_btn': 'Εγγραφή',
      'auth_or_social': 'Ή συνεχίστε με:',
      'auth_google': 'Συνέχεια με Google',
      'auth_apple': 'Συνέχεια με Apple',
      'auth_facebook': 'Συνέχεια με Facebook',
      'auth_switch_to_register': 'Δεν έχετε λογαριασμό; Εγγραφείτε εδώ!',
      'auth_switch_to_login': 'Έχετε ήδη λογαριασμό; Συνδεθείτε!',
      'auth_logout_btn': 'Αποσύνδεση',
      'auth_logged_in_as': 'Συνδεδεμένος ως:',
      'auth_btn_main': 'Σύνδεση & Λογαριασμός 👤',
      'lang_title': 'Επιλογή Γλώσσας',

      'terms_acceptance': 'Αποδέχομαι τους Όρους & Προϋποθέσεις και την πολιτική απορρήτου GDPR.',
      'role_guest': 'Επισκέπτης',
      'role_free': 'ΔΩΡΕΑΝ',
      'role_annual': 'Ετήσιος Συνεργάτης ⭐',
      'role_annual_price': '€240 (€20/μήνα)',
      'role_half_year': 'Εξάμηνος Συνεργάτης',
      'role_half_year_price': '€180 (6 μήνες)',

      'btn_stripe_annual': 'Πληρωμή Stripe & Εγγραφή (€240/έτος)',
      'btn_stripe_half': 'Πληρωμή Stripe & Εγγραφή (€180/6 μήνες)',
      'btn_guest_reg': 'Δωρεάν Εγγραφή Επισκέπτη',

      'transfer_title': 'Μεταφορά Αεροδρομίου ✈️🚖',
      'transfer_header_title': 'Αξιόπιστες Μεταφορές',
      'transfer_header_desc': 'Μεταφορές σταθερής τιμής από τα αεροδρόμια Λάρνακας & Πάφου.',
      'transfer_step1_title': '1. Κατεύθυνση Μεταφοράς',
      'transfer_dir_to_stay': 'Αεροδρόμιο ➔ Διαμονή',
      'transfer_dir_to_airport': 'Διαμονή ➔ Αεροδρόμιο',
      'transfer_step2_title': '2. Στοιχεία Πτήσης & Προορισμού',
      'transfer_dest_hint': 'Όνομα Διαμονής / Πόλης',
      'transfer_flight_num': 'Αριθμός Πτήσης (π.χ. W6 2451)',
      'transfer_phone_hint': 'Τηλέφωνο / Επαφή WhatsApp *',
      'transfer_submit_btn': 'Αίτηση Προσφοράς Μεταφοράς (WhatsApp) 🚖',
      'transfer_fill_required': 'Παρακαλώ συμπληρώστε τον προορισμό και τα στοιχεία επικοινωνίας!',

      'choose_property_type': 'Επιλέξτε τύπο ακινήτου 🏠',
      'rent_apartments': 'Διαμερίσματα & Ενοικίαση',
      'rent_apartments_desc': 'Μακroχρόνιες ή βραχυπρόθεσμες ενοικιάσεις.',
      'sale_properties': 'Ακίνητα προς Πώληση & Βίλες',
      'sale_properties_desc': 'Παραθαλάσσια ακίνητα και επενδύσεις.',
    },

    'de': {
      'slogan': 'Entdecken Sie Zypern: Unterkünfte, Genuss & Touren',
      'search_region_hint': 'Wählen Sie eine Region oder Stadt...',
      'cat_accommodations': 'Wohnungen\n& Immobilien',
      'cat_experiences': 'Erlebnisse\n& Touren',
      'cat_gastronomy': 'Gastronomie\n& Bars',
      'cat_transfer': 'Flughafen-\ntransfer ✈️',
      'nearby_search_bar': 'Autovermietung, Apotheken, Geschäfte in der Nähe...',
      'nearby_services_title': 'Dienste in der Nähe auf der Karte 🗺️',
      'choose_region_title': 'Wählen Sie ein Ziel auf Zypern 🏝️',
      'view_details': 'Anzeigen',
      'featured_badge': 'EMPFOHLEN',
      'all_regions': 'Alle Regionen',

      'auth_login_title': 'CYVESTA Anmelden',
      'auth_register_title': 'Neues Konto erstellen',
      'auth_desc': 'Speichern Sie Ihre Favoriten und verwalten Sie Buchungen!',
      'auth_email_hint': 'E-Mail-Adresse',
      'auth_password_hint': 'Passwort',
      'auth_name_hint': 'Vollständiger Name',
      'auth_business_name_hint': 'Unternehmens- / Gastgebername',
      'auth_tax_hint': 'Firmendaten / Steuernummer',
      'auth_address_hint': 'Adresse (Stadt, Straße, Hausnummer)',
      'auth_phone_hint': 'Telefonnummer',
      'auth_forgot_pass': 'Passwort vergessen?',
      'auth_login_btn': 'Anmelden',
      'auth_register_btn': 'Registrieren',
      'auth_or_social': 'Oder fortfahren mit:',
      'auth_google': 'Mit Google fortfahren',
      'auth_apple': 'Mit Apple fortfahren',
      'auth_facebook': 'Mit Facebook fortfahren',
      'auth_switch_to_register': 'Kein Konto? Hier registrieren!',
      'auth_switch_to_login': 'Bereits ein Konto? Anmelden!',
      'auth_logout_btn': 'Abmelden',
      'auth_logged_in_as': 'Angemeldet als:',
      'auth_btn_main': 'Anmelden & Konto 👤',
      'lang_title': 'Sprache auswählen',

      'terms_acceptance': 'Ich akzeptiere die AGB und die DSGVO-Datenschutzbestimmungen.',
      'role_guest': 'Gast',
      'role_free': 'KOSTENLOS',
      'role_annual': 'Jahres-Partner ⭐',
      'role_annual_price': '€240 (€20/Mo.)',
      'role_half_year': '6-Monats-Partner',
      'role_half_year_price': '€180 (6 Mo.)',

      'btn_stripe_annual': 'Stripe Zahlung & Registrierung (€240/Jahr)',
      'btn_stripe_half': 'Stripe Zahlung & Registrierung (€180/6 Mon.)',
      'btn_guest_reg': 'Kostenlose Gast-Registrierung',

      'transfer_title': 'Flughafentransfer ✈️🚖',
      'transfer_header_title': 'Zuverlässige Transfers',
      'transfer_header_desc': 'Festpreis-Transfers von den Flughäfen Larnaca & Paphos.',
      'transfer_step1_title': '1. Transfer-Richtung',
      'transfer_dir_to_stay': 'Flughafen ➔ Unterkunft',
      'transfer_dir_to_airport': 'Unterkunft ➔ Flughafen',
      'transfer_step2_title': '2. Flug- & Ziel-Details',
      'transfer_dest_hint': 'Name der Unterkunft / Stadt',
      'transfer_flight_num': 'Flugnummer (z. B. W6 2451)',
      'transfer_phone_hint': 'Telefonnummer / WhatsApp-Kontakt *',
      'transfer_submit_btn': 'Transfer-Angebot anfordern (WhatsApp) 🚖',
      'transfer_fill_required': 'Bitte geben Sie den Zielort und die Kontaktdaten ein!',

      'choose_property_type': 'Immobilientyp wählen 🏠',
      'rent_apartments': 'Wohnungen & Mieten',
      'rent_apartments_desc': 'Lang- oder kurzfristige Mieten auf Zypern.',
      'sale_properties': 'Immobilien zum Verkauf & Villen',
      'sale_properties_desc': 'Direkte Strandimmobilien und Investitionen.',
    },

    'ru': {
      'slogan': 'Откройте для себя Кипр: Жилье, Вкусы и Туры',
      'search_region_hint': 'Выберите регион или город...',
      'cat_accommodations': 'Апартаменты\nи Недвижимость',
      'cat_experiences': 'Впечатления\nи Туры',
      'cat_gastronomy': 'Гастрономия\nи Бары',
      'cat_transfer': 'Трансфер\nиз аэропорта ✈️',
      'nearby_search_bar': 'Прокат авто, аптеки, магазины рядом...',
      'nearby_services_title': 'Услуги рядом на карте 🗺️',
      'choose_region_title': 'Выберите направление на Кипре 🏝️',
      'view_details': 'Подробнее',
      'featured_badge': 'РЕКОМЕНДУЕМ',
      'all_regions': 'Все регионы',

      'auth_login_title': 'Вход в CYVESTA',
      'auth_register_title': 'Создать аккаунт',
      'auth_desc': 'Сохраняйте избранное и управляйте бронированиями!',
      'auth_email_hint': 'Эл. почта',
      'auth_password_hint': 'Пароль',
      'auth_name_hint': 'Имя и фамилия',
      'auth_business_name_hint': 'Название компании / Хозяина',
      'auth_tax_hint': 'Реквизиты / ИНН компании',
      'auth_address_hint': 'Адрес (Город, улица, дом)',
      'auth_phone_hint': 'Номер телефона',
      'auth_forgot_pass': 'Забыли пароль?',
      'auth_login_btn': 'Войти',
      'auth_register_btn': 'Регистрация',
      'auth_or_social': 'Или продолжить через:',
      'auth_google': 'Продолжить с Google',
      'auth_apple': 'Продолжить с Apple',
      'auth_facebook': 'Продолжить с Facebook',
      'auth_switch_to_register': 'Нет аккаунта? Зарегистрируйтесь!',
      'auth_switch_to_login': 'Уже есть аккаунт? Войдите!',
      'auth_logout_btn': 'Выйти',
      'auth_logged_in_as': 'Вы вошли как:',
      'auth_btn_main': 'Вход и Профиль 👤',
      'lang_title': 'Выберите язык',

      'terms_acceptance': 'Я принимаю Условия использования и политику конфиденциальности GDPR.',
      'role_guest': 'Гость',
      'role_free': 'БЕСПЛАТНО',
      'role_annual': 'Годовой партнер ⭐',
      'role_annual_price': '€240 (€20/мес)',
      'role_half_year': 'Партнер на 6 мес.',
      'role_half_year_price': '€180 (6 мес.)',

      'btn_stripe_annual': 'Оплата Stripe и регистрация (€240/год)',
      'btn_stripe_half': 'Оплата Stripe и регистрация (€180/6 мес.)',
      'btn_guest_reg': 'Бесплатная регистрация гостя',

      'transfer_title': 'Трансфер из аэропорта ✈️🚖',
      'transfer_header_title': 'Надежные трансферы на Кипре',
      'transfer_header_desc': 'Трансферы по фиксированной цене из аэропортов Ларнаки и Пафоса.',
      'transfer_step1_title': '1. Направление трансфера',
      'transfer_dir_to_stay': 'Аэропорт ➔ Проживание',
      'transfer_dir_to_airport': 'Проживание ➔ Аэропорт',
      'transfer_step2_title': '2. Детали рейса и пункта назначения',
      'transfer_dest_hint': 'Название жилья / Город',
      'transfer_flight_num': 'Номер рейса (например, W6 2451)',
      'transfer_phone_hint': 'Номер телефона / Контакт WhatsApp *',
      'transfer_submit_btn': 'Запросить расчет трансфера (WhatsApp) 🚖',
      'transfer_fill_required': 'Пожалуйста, введите пункт назначения и контактные данные!',

      'choose_property_type': 'Выберите тип недвижимости 🏠',
      'rent_apartments': 'Апартаменты и Аренда',
      'rent_apartments_desc': 'Долгосрочная или краткосрочная аренда на Кипре.',
      'sale_properties': 'Недвижимость на продажу и Виллы',
      'sale_properties_desc': 'Объекты на первой линии моря и инвестиции.',
    },
  };

  static String tr(String key) {
    final lang = currentLocale.value;
    if (_dict.containsKey(lang) && _dict[lang]!.containsKey(key)) {
      return _dict[lang]![key]!;
    }
    if (_dict['en'] != null && _dict['en']!.containsKey(key)) {
      return _dict['en']![key]!;
    }
    if (_dict['hu'] != null && _dict['hu']!.containsKey(key)) {
      return _dict['hu']![key]!;
    }
    return key;
  }
}