import 'package:flutter/material.dart';

class AppLanguage {
  static final ValueNotifier<String> currentLocale = ValueNotifier<String>('en');

  static void setLanguage(String langCode) {
    currentLocale.value = langCode;
  }

  static final Map<String, Map<String, String>> _dict = {
    'hu': {
      'slogan': 'Fedezd fel Ciprust: Szállások, Ízek & Túrák',
      'search_region_hint': 'Válassz ciprusi régiót vagy várost...',
      'cat_accommodations': 'Apartmanok\n& Ingatlanok',
      'cat_experiences': 'Élmények\n& Túrák',
      'cat_gastronomy': 'Gasztronómia\n& Bárok',
      'cat_transfer': 'Reptéri\ntranszfer ✈️',
      'nearby_search_bar': 'Autóbérlés, patikák, boltok a közeledben...',
      'nearby_services_title': 'Közeli szolgáltatások térképen 🗺️',
      'choose_region_title': 'Válassz ciprusi úti célt 🏝️',
      'view_details': 'Megtekintés',
      'featured_badge': 'KIEMELT',
      'all_regions': 'Összes régió (Egész Ciprus)',

      'auth_login_title': 'CYVESTA Bejelentkezés',
      'auth_register_title': 'Új Fiók Létrehozása',
      'auth_desc': 'Mentsd el kedvenceidet és kezeld a foglalásaidat!',
      'auth_email_hint': 'E-mail cím',
      'auth_password_hint': 'Jelszó',
      'auth_name_hint': 'Teljes név',
      'auth_business_name_hint': 'Vállalkozás / Szállásadó Neve',
      'auth_tax_hint': 'Hivatalos cégadatok / Adószám',
      'auth_address_hint': 'Cím (Település, utca, házszám)',
      'auth_phone_hint': 'Telefonszám',
      'auth_forgot_pass': 'Elfelejtetted a jelszavadat?',
      'auth_login_btn': 'Bejelentkezés',
      'auth_register_btn': 'Regisztráció',
      'auth_or_social': 'Vagy folytasd a következőkkel:',
      'auth_google': 'Folytatás Google fiókkal',
      'auth_apple': 'Folytatás Apple fiókkal',
      'auth_facebook': 'Folytatás Facebook fiókkal',
      'auth_switch_to_register': 'Nincs még fiókod? Regisztrálj itt!',
      'auth_switch_to_login': 'Már van fiókod? Jelentkezz be!',
      'auth_logout_btn': 'Kijelentkezés',
      'auth_logged_in_as': 'Bejelentkezve mint:',
      'auth_btn_main': 'Bejelentkezés & Fiók 👤',
      'lang_title': 'Nyelv kiválasztása / Language',

      'terms_acceptance': 'Elfogadom az ÁSZF-et és a ciprusi GDPR adatvédelmi irányelveket. *',
      'role_guest': 'Vendég',
      'role_free': 'INGYENES',
      'role_annual': 'Éves Partner ⭐',
      'role_annual_price': '€240 (€20/hó)',
      'role_half_year': 'Féléves Partner',
      'role_half_year_price': '€180 (6 hó)',

      'btn_stripe_annual': 'Stripe Fizetés & Regisztráció (€240/év)',
      'btn_stripe_half': 'Stripe Fizetés & Regisztráció (€180/6 hó)',
      'btn_guest_reg': 'Ingyenes Vendég Regisztráció',

      'transfer_title': 'Reptéri Transzfer ✈️🚖',
      'transfer_header_title': 'Megbízható Ciprusi Transzferek',
      'transfer_header_desc': 'Larnaca (LCA) és Paphos (PFO) repülőterekről fix áras transzferek.',
      'transfer_step1_title': '1. Transzfer Iránya',
      'transfer_dir_to_stay': 'Reptér ➔ Szállás',
      'transfer_dir_to_airport': 'Szállás ➔ Reptér',
      'transfer_step2_title': '2. Járat & Úti Cél Részletei',
      'transfer_dest_hint': 'Szállás / Város neve',
      'transfer_flight_num': 'Járatszám (pl. W6 2451)',
      'transfer_phone_hint': 'Telefonszámod / WhatsApp *',
      'transfer_submit_btn': 'Transzfer Árajánlat Kérése (WhatsApp) 🚖',
      'transfer_fill_required': 'Kérjük töltsd ki a célállomást és az elérhetőségedet!',

      'choose_property_type': 'Válassz ingatlan típust 🏠',
      'rent_apartments': 'Apartmanok & Kiadó lakások',
      'rent_apartments_desc': 'Hosszú vagy rövid távú bérlemények Cipruson.',
      'sale_properties': 'Eladó Ingatlanok & Villák',
      'sale_properties_desc': 'Közvetlen eladó tengerparti ingatlanok és befektetések.',

      'serv_car_rental': 'Autóbérlés',
      'serv_car_rental_desc': 'Bérelj autót egyszerűen Cipruson',
      'serv_bike_rental': 'Kerékpár bérlés',
      'serv_bike_rental_desc': 'Fedezd fel a tájat két keréken',
      'serv_pharmacy': 'Gyógyszertár',
      'serv_pharmacy_desc': 'Közel eső gyógyszertárak és ügyeletek',
      'serv_supermarket': 'Szupermarket',
      'serv_supermarket_desc': 'Bevásárlási lehetőségek a közelben',
      'serv_nightlife': 'Éjszakai élet',
      'serv_nightlife_desc': 'Bárok, klubok és szórakozóhelyek',
      'serv_bus_stop': 'Buszmegálló',
      'serv_bus_stop_desc': 'Tömegközlekedési megállók',
      'serv_atm': 'ATM / Bankautomata',
      'serv_atm_desc': 'Készpénzfelvételi lehetőségek',
      
      'calendar_free': 'Szabad',
      'calendar_booked': 'Foglalt',
      'calendar_pending': 'Függőben',
      'calendar_section_title': 'Foglaltsági Naptár & iCal 📅',
      'details_section_title': 'Leírás & Részletek 📖',
      'selected_dates_label': 'Kiválasztott dátumok:',
      'total_price_label': 'Összesen:',
      
      'desc_sale': 'Gyönyörű tengerparti exkluzív ingatlan Cipruson, prémium felszereltséggel, saját medencével, modern gépészettel és lenyűgöző kilátással. Ideális befektetés vagy luxus otthon.',
      'desc_rent': 'Gyönyörű szálláshely prémium felszereltséggel, kiváló elhelyezkedéssel és kényelmi szolgáltatásokkal a tökéletes ciprusi pihenéshez.',
      'book_table_btn': 'Asztalfoglalás 🍽️',

      'month_july': 'Július 2026',
      'day_mo': 'HÉ',
      'day_tu': 'KE',
      'day_we': 'SZE',
      'day_th': 'CSÜ',
      'day_fr': 'PÉ',
      'day_sa': 'SZO',
      'day_su': 'VA',

      'btn_internal_chat': 'Belső Chat',
      'btn_select_date': 'Dátum kiválasztása 🗓️',
      'btn_modify': 'Módosítás ✍️',
      'btn_view_map': 'Megtekintés Térképen 🗺️',

      'profile_app_bar_title': 'Partner Profil & Regisztráció',
      'profile_section_title': 'Szállásadó / Partner Adatok (Kötelező)',
      'profile_register_btn_text': 'Partner Regisztráció & Validáló E-mail küldése',

      'notif_page_title': 'Értesítések Beállítása',
      'notif_last_minute_title': 'Last Minute Akciók',
      'notif_last_minute_desc': 'Értesítsen, ha villámakciók érhetőek el',

      'btn_table_reservation': 'Asztalfoglalás 🍽️',
      'btn_call_restaurant': 'Hívás / Asztal',
      'label_opening_hours': 'Nyitvatartás',
      'label_menu_preview': 'Menü & Részletek',

      'faq_page_title': 'Gyakori Kérdések & Működés 💡',
      'faq_header_title': 'A Jövő Ciprusi Élményplatformja',
      'faq_header_desc': 'Közvetlen kapcsolat, 0% jutalék, ellenőrzött szállások és villámgyors Last Minute Push értesítések.',
      'faq_q1': 'Mi a CYVESTA, és miben különbözik egy hagyományos weboldaltól?',
      'faq_a1': 'A CYVESTA egy dedikált, egész Ciprust lefedő prémium mobilplatform. Míg egy átlagos weboldal lassú, bonyolult és tele van zavaró hirdetésekkel, a CYVESTA natív sebességgel működik, közvetlen WhatsApp kapcsolatot biztosít a tulajdonosokkal, élő iCal naptárszinkronizációt nyújt, és GPS-alapú térképen mutatja a legjobb villákat, strandokat, éttermeket és reptéri transzfereket.',
      'faq_q2': 'Hogyan működnek a Last Minute & Villámakció Push Értesítések? ⚡',
      'faq_a2': 'Ha egy szálláson váratlan lemondás történik, vagy üresen maradt néhány nap, a tulajdonos közvetlenül a mobilappból (admin gépelés nélkül, 30 másodperc alatt) elindíthat egy villámakciót. \n\n• Tulajdonos szemszöge: Megadja a felszabadult dátumot és a kedvezményes árat (pl. -35%), majd rányom a küldés gombra.\n• Vendég szemszöge: Azok a felhasználók, akik feliratkoztak a Last Minute értesítésekre vagy elmentették a szállást a kedvenceik közé, azonnal Push értesítést kapnak a telefonjukra (pl. "Paphos Beachfront Villa felszabadult aug. 20-24. között! Csak most €75/éj").\n• Eredmény: Villámgyors foglalás és közvetlen WhatsApp kapcsolat!',
      'faq_q3': 'Miért éri meg jobban a CYVESTA, mint a Booking vagy az Airbnb?',
      'faq_a3': 'A nagy szállásközvetítő portálok 15-25% jutalékot vonnak le mind a vendégtől, mind a szállásadótól. A CYVESTA-nál 0% a jutalék! A vendég közvetlenül a tulajdonossal tárgyal WhatsApp-on, a partner pedig a teljes bevételt (100%) megtartja, rejtett költségek nélkül.',
      'faq_q4': 'Mennyibe kerül a vendégeknek az applikáció használata?',
      'faq_a4': 'A vendégek és utazók számára a CYVESTA használata 100%-ban INGYENES (0 EUR). Nincs regisztrációs díj, sem foglalási felár. Ingyenesen böngészheted az eladó és kiadó ingatlanokat, mentheted kedvenceidet és közvetlenül írhatsz a házigazdáknak.',
      'faq_q5': 'Hogyan hirdethetnek a szállásadók, éttermek és túraszervezők?',
      'faq_a5': 'A partnerek rendkívül kedvező, fix tagsági díjjal csatlakozhatnak:\n• Éves Partner Tagság: €240 / év (mindössze €20 / hó!)\n• Féléves Partner Tagság: €180 / félév (havi €30)\nA tagság azonnal aktiválható a biztonságos Stripe bankkártyás felületen keresztül, és azonnali megjelenést biztosít a kezdőlapon, a térképen és a kategóriákban.',
      'faq_q6': 'Hogyan működik az élő iCal naptárszinkronizáció?',
      'faq_a6': 'A szállásadó egyszerűen beilleszti az Airbnb vagy Booking naptárának .ics linkjét a hirdetésébe. A CYVESTA automatikusan szinkronizálja a foglaltságot, így a vendégek csak a valóban szabad időpontokat látják és jelölhetik ki. Ezzel a kettős foglalás (overbooking) teljes mértékben kizárt!',
      'faq_q7': 'Hol érhető el a hivatalos ÁSZF és GDPR adatvédelmi szabályzat?',
      'faq_a7': 'A CYVESTA teljes körű Általános Szerződési Feltételei és ciprusi jogszabályoknak megfelelő GDPR adatvédelmi tájékoztatója az alábbi hivatalos dokumentumban olvasható részletesen:',
      'faq_doc_link': '📂 Hivatalos ÁSZF & GDPR Google Dokumentum megnyitása',
      'faq_footer_title': 'Csatlakozz te is Partnerként!',
      'faq_footer_desc': 'Közvetlen WhatsApp foglalások és Last Minute Push elérés mindössze €20/hó díjért.',
      'faq_footer_btn': 'Partner Csomagok Megtekintése 💎',
    },

    'en': {
      'slogan': 'Discover Cyprus: Stays, Tastes & Tours',
      'search_region_hint': 'Select a Cyprus region or city...',
      'cat_accommodations': 'Apartments\n& Real Estate',
      'cat_experiences': 'Experiences\n& Tours',
      'cat_gastronomy': 'Dining\n& Bars',
      'cat_transfer': 'Airport\nTransfer ✈️',
      'nearby_search_bar': 'Car rentals, pharmacies, stores near you...',
      'nearby_services_title': 'Nearby Services on Map 🗺️',
      'choose_region_title': 'Choose Destination in Cyprus 🏝️',
      'view_details': 'View Details',
      'featured_badge': 'FEATURED',
      'all_regions': 'All Regions (Whole Cyprus)',

      'auth_login_title': 'CYVESTA Sign In',
      'auth_register_title': 'Create New Account',
      'auth_desc': 'Save your favorites and manage bookings!',
      'auth_email_hint': 'Email Address',
      'auth_password_hint': 'Password',
      'auth_name_hint': 'Full Name',
      'auth_business_name_hint': 'Business / Host Name',
      'auth_tax_hint': 'Company Details / Tax Number',
      'auth_address_hint': 'Address (City, Street, House No.)',
      'auth_phone_hint': 'Phone Number',
      'auth_forgot_pass': 'Forgot your password?',
      'auth_login_btn': 'Sign In',
      'auth_register_btn': 'Register',
      'auth_or_social': 'Or continue with:',
      'auth_google': 'Continue with Google',
      'auth_apple': 'Continue with Apple',
      'auth_facebook': 'Continue with Facebook',
      'auth_switch_to_register': "Don't have an account? Sign up here!",
      'auth_switch_to_login': 'Already have an account? Sign in!',
      'auth_logout_btn': 'Log Out',
      'auth_logged_in_as': 'Logged in as:',
      'auth_btn_main': 'Sign In & Account 👤',
      'lang_title': 'Select Language',

      'terms_acceptance': 'I accept the Terms & Conditions and Cyprus GDPR privacy policies. *',
      'role_guest': 'Guest',
      'role_free': 'FREE',
      'role_annual': 'Annual Partner ⭐',
      'role_annual_price': '€240 (€20/mo)',
      'role_half_year': '6-Month Partner',
      'role_half_year_price': '€180 (6 mo)',

      'btn_stripe_annual': 'Stripe Payment & Registration (€240/year)',
      'btn_stripe_half': 'Stripe Payment & Registration (€180/6 months)',
      'btn_guest_reg': 'Free Guest Registration',

      'transfer_title': 'Airport Transfer ✈️🚖',
      'transfer_header_title': 'Reliable Cyprus Airport Transfers',
      'transfer_header_desc': 'Fixed-price transfers from Larnaca & Paphos airports.',
      'transfer_step1_title': '1. Transfer Direction',
      'transfer_dir_to_stay': 'Airport ➔ Stay',
      'transfer_dir_to_airport': 'Stay ➔ Airport',
      'transfer_step2_title': '2. Flight & Destination Details',
      'transfer_dest_hint': 'Stay / City name',
      'transfer_flight_num': 'Flight Number (e.g. W6 2451)',
      'transfer_phone_hint': 'Phone Number / WhatsApp Contact *',
      'transfer_submit_btn': 'Request Transfer Quote (WhatsApp) 🚖',
      'transfer_fill_required': 'Please enter destination and contact details!',

      'choose_property_type': 'Choose Property Type 🏠',
      'rent_apartments': 'Apartments & Rentals',
      'rent_apartments_desc': 'Long or short term rentals in Cyprus.',
      'sale_properties': 'Properties for Sale & Villas',
      'sale_properties_desc': 'Direct beachfront properties and investments.',

      'serv_car_rental': 'Car Rental',
      'serv_car_rental_desc': 'Rent a car easily in Cyprus',
      'serv_bike_rental': 'Bike Rental',
      'serv_bike_rental_desc': 'Explore the scenery on two wheels',
      'serv_pharmacy': 'Pharmacy',
      'serv_pharmacy_desc': 'Nearby pharmacies and on-call services',
      'serv_supermarket': 'Supermarket',
      'serv_supermarket_desc': 'Shopping options nearby',
      'serv_nightlife': 'Nightlife',
      'serv_nightlife_desc': 'Bars, clubs and entertainment',
      'serv_bus_stop': 'Bus Stop',
      'serv_bus_stop_desc': 'Public transport stops',
      'serv_atm': 'ATM / Cash Machine',
      'serv_atm_desc': 'Cash withdrawal points',
      
      'calendar_free': 'Available',
      'calendar_booked': 'Booked',
      'calendar_pending': 'Pending',
      'calendar_section_title': 'Booking Calendar & iCal 📅',
      'details_section_title': 'Description & Details 📖',
      'selected_dates_label': 'Selected dates:',
      'total_price_label': 'Total:',
      
      'desc_sale': 'Beautiful beachfront exclusive property in Cyprus with premium amenities, private pool, modern engineering and stunning views. Ideal investment or luxury home.',
      'desc_rent': 'Beautiful accommodation with premium equipment, excellent location and convenient services for the perfect Cyprus holiday.',
      'book_table_btn': 'Book a Table 🍽️',

      'month_july': 'July 2026',
      'day_mo': 'MO',
      'day_tu': 'TU',
      'day_we': 'WE',
      'day_th': 'TH',
      'day_fr': 'FR',
      'day_sa': 'SA',
      'day_su': 'SU',

      'btn_internal_chat': 'Internal Chat',
      'btn_select_date': 'Select Date 🗓️',
      'btn_modify': 'Modify ✍️',
      'btn_view_map': 'View on Map 🗺️',

      'profile_app_bar_title': 'Partner Profile & Registration',
      'profile_section_title': 'Host / Partner Details (Required)',
      'profile_register_btn_text': 'Partner Registration & Send Verification Email',

      'notif_page_title': 'Notification Settings',
      'notif_last_minute_title': 'Last Minute Deals',
      'notif_last_minute_desc': 'Notify me when flash deals are available',

      'btn_table_reservation': 'Table Reservation 🍽️',
      'btn_call_restaurant': 'Call Restaurant',
      'label_opening_hours': 'Opening Hours',
      'label_menu_preview': 'Menu & Details',

      'faq_page_title': 'How CYVESTA Works 💡',
      'faq_header_title': 'The Next Generation Cyprus Platform',
      'faq_header_desc': 'Direct connections, 0% commissions, verified local hosts, and instant Last Minute Push notifications.',
      'faq_q1': 'What is CYVESTA and how is it different from a normal website?',
      'faq_a1': 'CYVESTA is an all-in-one luxury mobile ecosystem for Cyprus. Unlike standard websites that are slow and cluttered, CYVESTA offers lightning-fast native performance, direct WhatsApp host communication, live iCal calendar synchronization, and interactive GPS map discovery.',
      'faq_q2': 'How do Last Minute & Flash Deal Push Notifications work? ⚡',
      'faq_a2': 'When a cancellation occurs or dates open up, hosts can trigger a flash deal directly from their mobile app within 30 seconds.\n\n• Host perspective: Enter open dates and discounted price (e.g. -35%), then hit send.\n• Guest perspective: Users subscribed to Last Minute deals or who bookmarked the property receive an instant push notification on their phone.\n• Result: Lightning-fast bookings via direct WhatsApp chat!',
      'faq_q3': 'Why is CYVESTA better than Airbnb or Booking.com?',
      'faq_a3': 'Major booking platforms take 15-25% commission from both guests and hosts. CYVESTA charges 0% commission! Guests connect directly with hosts via WhatsApp, and property owners keep 100% of their revenue.',
      'faq_q4': 'Is the app free for guests and travelers?',
      'faq_a4': 'Yes, CYVESTA is 100% FREE for guests. There are no registration fees or hidden booking surcharges.',
      'faq_q5': 'How can hosts and businesses list their properties?',
      'faq_a5': 'Hosts can join with transparent flat membership plans:\n• Annual Partner Membership: €240 / year (only €20 / month!)\n• 6-Month Partner Membership: €180 / 6 months\nInstant activation via secure Stripe payment.',
      'faq_q6': 'How does live iCal calendar synchronization work?',
      'faq_a6': 'Hosts paste their Airbnb or Booking.com .ics link to automatically sync availability and prevent double bookings.',
      'faq_q7': 'Where can I find the official Terms & Conditions and GDPR policy?',
      'faq_a7': 'The complete CYVESTA Terms of Service and Cyprus-compliant GDPR privacy policy can be reviewed via the official document:',
      'faq_doc_link': '📂 Open Official Terms & GDPR Google Document',
      'faq_footer_title': 'Ready to List Your Property?',
      'faq_footer_desc': 'Get direct WhatsApp bookings and Last Minute reach for only €20/month (€240/year).',
      'faq_footer_btn': 'View Partner Plans 💎',
    },

    'el': {
      'slogan': 'Ανακαλύψτε την Κύπρο: Διαμονή, Γεύσεις & Εκδρομές',
      'search_region_hint': 'Επιλέξτε περιοχή ή πόλη...',
      'cat_accommodations': 'Διαμερίσματα\n& Ακίνητα',
      'cat_experiences': 'Εμπειρίες\n& Εκδρομές',
      'cat_gastronomy': 'Γαστρονομία\n& Μπαρ',
      'cat_transfer': 'Μεταφορά\nΑεροδρομίου ✈️',
      'nearby_search_bar': 'Ενοικίαση αυτοκινήτων, φαρμακεία, καταστήματα κοντά σας...',
      'nearby_services_title': 'Υπηρεσίες στον χάρτη 🗺️',
      'choose_region_title': 'Επιλέξτε προορισμό στην Κύπρο 🏝️',
      'view_details': 'Προβολή',
      'featured_badge': 'ΠΡΟΤΕΙΝΟΜΕΝo',
      'all_regions': 'Όλες οι περιοχές',

      'auth_login_title': 'Σύνδεση CYVESTA',
      'auth_register_title': 'Δημιουργία Λογαριασμού',
      'auth_desc': 'Αποθηκεύστε τα αγαπημένα σας και διαχειριστείτε τις κρατήσεις σας!',
      'auth_email_hint': 'Διεύθυνση Email',
      'auth_password_hint': 'Κωδικός πρόσβασης',
      'auth_name_hint': 'Ονοματεπώνυμο',
      'auth_business_name_hint': 'Όνομα Επιχείρησης / Οικοδεσπότη',
      'auth_tax_hint': 'Στοιχεία Εταιρείας / ΑΦΜ',
      'auth_address_hint': 'Διεύθυνση (Πόλη, Οδός, Αριθμός)',
      'auth_phone_hint': 'Αριθμός Τηλεφώνου',
      'auth_forgot_pass': 'Ξεχάσατε τον κωδικό σας;',
      'auth_login_btn': 'Σύνδεση',
      'auth_register_btn': 'Εγγραφή',
      'auth_or_social': 'Ή συνεχίστε με:',
      'auth_google': 'Συνέχεια με Google',
      'auth_apple': 'Συνέχεια με Apple',
      'auth_facebook': 'Συνέχεια με Facebook',
      'auth_switch_to_register': 'Δεν έχετε λογαριασμό; Εγγραφείτε εδώ!',
      'auth_switch_to_login': 'Έχετε ήδη λογαριασμό; Συνδεθείτε!',
      'auth_logout_btn': 'Αποσύνδεση',
      'auth_logged_in_as': 'Συνδεδεμένος ως:',
      'auth_btn_main': 'Σύνδεση & Λογαριασμός 👤',
      'lang_title': 'Επιλογή Γλώσσας',

      'terms_acceptance': 'Αποδέχομαι τους Όρους & Προϋποθέσεις και την πολιτική απορρήτου GDPR. *',
      'role_guest': 'Επισκέπτης',
      'role_free': 'ΔΩΡΕΑΝ',
      'role_annual': 'Ετήσιος Συνεργάτης ⭐',
      'role_annual_price': '€240 (€20/μήνα)',
      'role_half_year': 'Εξάμηνος Συνεργάτης',
      'role_half_year_price': '€180 (6 μήνες)',

      'btn_stripe_annual': 'Πληρωμή Stripe & Εγγραφή (€240/έτος)',
      'btn_stripe_half': 'Πληρωμή Stripe & Εγγραφή (€180/6 μήνες)',
      'btn_guest_reg': 'Δωρεάν Εγγραφή Επισκέπτη',

      'transfer_title': 'Μεταφορά Αεροδρομίου ✈️🚖',
      'transfer_header_title': 'Αξιόπιστες Μεταφορές',
      'transfer_header_desc': 'Μεταφορές σταθερής τιμής από τα αεροδρόμια Λάρνακας & Πάφου.',
      'transfer_step1_title': '1. Κατεύθυνση Μεταφοράς',
      'transfer_dir_to_stay': 'Αεροδρόμιο ➔ Διαμονή',
      'transfer_dir_to_airport': 'Διαμονή ➔ Αεροδρόμιο',
      'transfer_step2_title': '2. Στοιχεία Πτήσης & Προορισμού',
      'transfer_dest_hint': 'Όνομα Διαμονής / Πόλης',
      'transfer_flight_num': 'Αριθμός Πτήσης (π.χ. W6 2451)',
      'transfer_phone_hint': 'Τηλέφωνο / Επαφή WhatsApp *',
      'transfer_submit_btn': 'Αίτηση Προσφοράς Μεταφοράς (WhatsApp) 🚖',
      'transfer_fill_required': 'Παρακαλώ συμπληρώστε τον προορισμό και τα στοιχεία επικοινωνίας!',

      'choose_property_type': 'Επιλέξτε τύπο ακινήτου 🏠',
      'rent_apartments': 'Διαμερίσματα & Ενοικίαση',
      'rent_apartments_desc': 'Μακροχρόνιες ή βραχυπρόθεσμες ενοικιάσεις.',
      'sale_properties': 'Ακίνητα προς Πώληση & Βίλες',
      'sale_properties_desc': 'Παραθαλάσσια ακίνητα και επενδύσεις.',

      'serv_car_rental': 'Ενοικίαση Αυτοκινήτου',
      'serv_car_rental_desc': 'Ενοικιάστε αυτοκίνητο εύκολα στην Κύπρο',
      'serv_bike_rental': 'Ενοικίαση ποδηλάτου',
      'serv_bike_rental_desc': 'Εξερευνήστε το τοπίο με δύο τροχούς',
      'serv_pharmacy': 'Φαρμακείο',
      'serv_pharmacy_desc': 'Κοντινά φαρμακεία',
      'serv_supermarket': 'Supermarket',
      'serv_supermarket_desc': 'Επιλογές για ψώνια κοντά σας',
      'serv_nightlife': 'Νυχτερινή Ζωή',
      'serv_nightlife_desc': 'Mπαρ, κλαμπ και διασκέδαση',
      'serv_bus_stop': 'Στάση Λεωφορείου',
      'serv_bus_stop_desc': 'Στάσεις δημόσιας συγκοινωνίας',
      'serv_atm': 'ATM',
      'serv_atm_desc': 'Σημεία ανάληψης μετρητών',
      
      'calendar_free': 'Διαθέσιμο',
      'calendar_booked': 'Κλεισμένο',
      'calendar_pending': 'Εκκρεμεί',
      'calendar_section_title': 'Ημερολόγιο & iCal 📅',
      'details_section_title': 'Περιγραφή & Λεπτομέρειες 📖',
      'selected_dates_label': 'Επιλεγμένες ημερομηνίες:',
      'total_price_label': 'Σύνολο:',
      
      'desc_sale': 'Όμορφο παραθαλάσσιο αποκλειστικό ακίνητο στην Κύπρο με premium παροχές, ιδιωτική πισίνα και εκπληκτική θέα.',
      'desc_rent': 'Όμορφο κατάλυμα με premium εξοπλισμό και εξαιρετική τοποθεσία για τέλειες διακοπές στην Κύπρο.',
      'book_table_btn': 'Κράτηση Τραπεζιού 🍽️',

      'month_july': 'Ιούλιος 2026',
      'day_mo': 'ΔΕ',
      'day_tu': 'ΤΡ',
      'day_we': 'ΤΕ',
      'day_th': 'ΠΕ',
      'day_fr': 'ΠΑ',
      'day_sa': 'ΣΑ',
      'day_su': 'ΚΥ',

      'btn_internal_chat': 'Εσωτερική Συνομιλία',
      'btn_select_date': 'Επιλογή Ημερομηνίας 🗓️',
      'btn_modify': 'Τροποποίηση ✍️',
      'btn_view_map': 'Προβολή στον Χάρτη 🗺️',

      'profile_app_bar_title': 'Προφίλ Συνεργάτη & Εγγραφή',
      'profile_section_title': 'Στοιχεία Οικοδεσπότη / Συνεργάτη (Υποχρεωτικά)',
      'profile_register_btn_text': 'Εγγραφή Συνεργάτη & Αποστολή Email Επιβεβαίωσης',

      'notif_page_title': 'Ρυθμίσεις Ειδοποιήσεων',
      'notif_last_minute_title': 'Προσφορές Last Minute',
      'notif_last_minute_desc': 'Ειδοποίηση όταν είναι διαθέσιμες προσφορές',

      'btn_table_reservation': 'Κράτηση Τραπεζιού 🍽️',
      'btn_call_restaurant': 'Κλήση',
      'label_opening_hours': 'Ώρες Λειτουργίας',
      'label_menu_preview': 'Μενού & Λεπτομέρειες',

      'faq_page_title': 'Συχνές Ερωτήσεις & Λειτουργία 💡',
      'faq_header_title': 'Η Πλατφόρμα Εμπειριών της Κύπρου',
      'faq_header_desc': 'Άμεση επικοινωνία, 0% προμήθεια, επαληθευμένα καταλύματα και άμεσες ειδοποιήσεις Last Minute Push.',
      'faq_q1': 'Τι είναι το CYVESTA και πώς διαφέρει από έναν συνηθισμένο ιστότοπο;',
      'faq_a1': 'Το CYVESTA είναι μια αποκλειστική πλατφόρμα κινητής τηλεφωνίας premium για ολόκληρη την Κύπρο. Παρέχει άμεση επικοινωνία μέσω WhatsApp, συγχρονισμό iCal σε πραγματικό χρόνο και διαδραστικό χάρτη GPS.',
      'faq_q2': 'Πώς λειτουργούν οι ειδοποιήσεις Last Minute & Flash Deal Push; ⚡',
      'faq_a2': 'Όταν προκύψει ακύρωση ή ανοίξουν ημερομηνίες, οι οικοδεσπότες μπορούν να ενεργοποιήσουν μια προσφορά απευθείας από την εφαρμογή εντός 30 δευτερολέπτων.',
      'faq_q3': 'Γιατί το CYVESTA είναι καλύτερο από το Booking ή την Airbnb;',
      'faq_a3': 'Οι μεγάλες πύλες κρατήσεων χρεώνουν 15-25% προμήθεια. Το CYVESTA χρεώνει 0% προμήθεια! Ο επισκέπτης διαπραγματεύεται απευθείας με τον ιδιοκτήτη.',
      'faq_q4': 'Πόσο κοστίζει στους επισκέπτες η χρήση της εφαρμογής;',
      'faq_a4': 'Για τους επισκέπτες και τους ταξιδιώτες, η χρήση του CYVESTA είναι 100% ΔΩΡΕΑΝ (0 EUR). Χωρίς τέλη εγγραφής ή επιβαρύνσεις κρατήσεων.',
      'faq_q5': 'Πώς μπορούν να διαφημιστούν οι ιδιοκτήτες και οι επιχειρήσεις;',
      'faq_a5': 'Οι συνεργάτες μπορούν να εγγραφούν με μια πολύ προσιτή, σταθερή συνδρομή: Ετήσια Συνδρομή €240 / έτος (€20 / μήνα).',
      'faq_q6': 'Πώς λειτουργεί ο συγχρονισμός ημερολογρίου iCal σε πραγματικό χρόνο;',
      'faq_a6': 'Ο ιδιοκτήτης απλώς επικοellά τον σύνδεσμο .ics του ημερολογρίου Airbnb ή Booking. Ο διπλός αποκλεισμός (overbooking) αποκλείεται πλήρως!',
      'faq_q7': 'Πού βρίσκονται οι επίσημοι Όροι και η πολιτική απορρήτου GDPR;',
      'faq_a7': 'Οι πλήρεις Όροι Χρήσης και η πολιτική απορρήτου GDPR είναι διαθέσιμοι στον ακόλουθο σύνδεσμο:',
      'faq_doc_link': '📂 Άνοιγμα Επίσημου Εγγράφου Όρων & GDPR',
      'faq_footer_title': 'Γίνετε Συνεργάτης Σήμερα!',
      'faq_footer_desc': 'Άμεσες κρατήσεις WhatsApp και πρόσβαση Last Minute Push με μόλις €20/μήνα.',
      'faq_footer_btn': 'Προβολή Πακέτων Συνεργατών 💎',
    },

    'de': {
      'slogan': 'Entdecken Sie Zypern: Unterkünfte, Genuss & Touren',
      'search_region_hint': 'Wählen Sie eine Region oder Stadt...',
      'cat_accommodations': 'Wohnungen\n& Immobilien',
      'cat_experiences': 'Erlebnisse\n& Touren',
      'cat_gastronomy': 'Gastronomie\n& Bars',
      'cat_transfer': 'Flughafen-\ntransfer ✈️',
      'nearby_search_bar': 'Autovermietung, Apotheken, Geschäfte in der Nähe...',
      'nearby_services_title': 'Dienste in der Nähe auf der Karte 🗺️',
      'choose_region_title': 'Wählen Sie ein Ziel auf Zypern 🏝️',
      'view_details': 'Anzeigen',
      'featured_badge': 'EMPFOHLEN',
      'all_regions': 'Alle Regionen',

      'auth_login_title': 'CYVESTA Anmelden',
      'auth_register_title': 'Neues Konto erstellen',
      'auth_desc': 'Speichern Sie Ihre Favoriten und verwalten Sie Buchungen!',
      'auth_email_hint': 'E-Mail-Adresse',
      'auth_password_hint': 'Passwort',
      'auth_name_hint': 'Vollständiger Name',
      'auth_business_name_hint': 'Unternehmens- / Gastgebername',
      'auth_tax_hint': 'Firmendaten / Steuernummer',
      'auth_address_hint': 'Adresse (Stadt, Straße, Hausnummer)',
      'auth_phone_hint': 'Telefonnummer',
      'auth_forgot_pass': 'Passwort vergessen?',
      'auth_login_btn': 'Anmelden',
      'auth_register_btn': 'Registrieren',
      'auth_or_social': 'Oder fortfahren mit:',
      'auth_google': 'Mit Google fortfahren',
      'auth_apple': 'Mit Apple fortfahren',
      'auth_facebook': 'Mit Facebook fortfahren',
      'auth_switch_to_register': 'Kein Konto? Hier registrieren!',
      'auth_switch_to_login': 'Bereits ein Konto? Anmelden!',
      'auth_logout_btn': 'Abmelden',
      'auth_logged_in_as': 'Angemeldet als:',
      'auth_btn_main': 'Anmelden & Konto 👤',
      'lang_title': 'Sprache auswählen',

      'terms_acceptance': 'Ich akzeptiere die AGB und die DSGVO-Datenschutzbestimmungen. *',
      'role_guest': 'Gast',
      'role_free': 'KOSTENLOS',
      'role_annual': 'Jahres-Partner ⭐',
      'role_annual_price': '€240 (€20/Mo.)',
      'role_half_year': '6-Monats-Partner',
      'role_half_year_price': '€180 (6 Mo.)',

      'btn_stripe_annual': 'Stripe Zahlung & Registrierung (€240/Jahr)',
      'btn_stripe_half': 'Stripe Zahlung & Registrierung (€180/6 Mon.)',
      'btn_guest_reg': 'Kostenlose Gast-Registrierung',

      'transfer_title': 'Flughafentransfer ✈️🚖',
      'transfer_header_title': 'Zuverlässige Transfers',
      'transfer_header_desc': 'Festpreis-Transfers von den Flughäfen Larnaca & Paphos.',
      'transfer_step1_title': '1. Transfer-Richtung',
      'transfer_dir_to_stay': 'Flughafen ➔ Unterkunft',
      'transfer_dir_to_airport': 'Unterkunft ➔ Flughafen',
      'transfer_step2_title': '2. Flug- & Ziel-Details',
      'transfer_dest_hint': 'Name der Unterkunft / Stadt',
      'transfer_flight_num': 'Flugnummer (z. B. W6 2451)',
      'transfer_phone_hint': 'Telefonnummer / WhatsApp-Kontakt *',
      'transfer_submit_btn': 'Transfer-Angebot anfordern (WhatsApp) 🚖',
      'transfer_fill_required': 'Bitte geben Sie den Zielort und die Kontaktdaten ein!',

      'choose_property_type': 'Immobilientyp wählen 🏠',
      'rent_apartments': 'Wohnungen & Mieten',
      'rent_apartments_desc': 'Lang- oder kurzfristige Mieten auf Zypern.',
      'sale_properties': 'Immobilien zum Verkauf & Villen',
      'sale_properties_desc': 'Direkte Strandimmobilien und Investitionen.',

      'serv_car_rental': 'Autovermietung',
      'serv_car_rental_desc': 'Mieten Sie ganz einfach ein Auto auf Zypern',
      'serv_bike_rental': 'Fahrradverleih',
      'serv_bike_rental_desc': 'Erkunden Sie die Landschaft auf zwei Rädern',
      'serv_pharmacy': 'Apotheke',
      'serv_pharmacy_desc': 'Apotheken in der Nähe',
      'serv_supermarket': 'Supermarkt',
      'serv_supermarket_desc': 'Einkaufsmöglichkeiten in der Nähe',
      'serv_nightlife': 'Nachtleben',
      'serv_nightlife_desc': 'Bars, Clubs und Unterhaltung',
      'serv_bus_stop': 'Bushaltestelle',
      'serv_bus_stop_desc': 'Öffentliche Verkehrsmittel',
      'serv_atm': 'ATM / Geldautomat',
      'serv_atm_desc': 'Geldabhebepunkte',
      
      'calendar_free': 'Verfügbar',
      'calendar_booked': 'Gebucht',
      'calendar_pending': 'Ausstehend',
      'calendar_section_title': 'Belegungskalender & iCal 📅',
      'details_section_title': 'Beschreibung & Details 📖',
      'selected_dates_label': 'Ausgewählte Daten:',
      'total_price_label': 'Gesamt:',
      
      'desc_sale': 'Wunderschöne exklusive Strandimmobilie auf Zypern mit erstklassiger Ausstattung, privatem Pool und herrlichem Blick.',
      'desc_rent': 'Schöne Unterkunft mit erstklassiger Ausstattung und hervorragender Lage für den perfekten Zypern-Urlaub.',
      'book_table_btn': 'Tisch reservieren 🍽️',

      'month_july': 'Juli 2026',
      'day_mo': 'MO',
      'day_tu': 'DI',
      'day_we': 'MI',
      'day_th': 'DO',
      'day_fr': 'FR',
      'day_sa': 'SA',
      'day_su': 'SO',

      'btn_internal_chat': 'Interner Chat',
      'btn_select_date': 'Datum auswählen 🗓️',
      'btn_modify': 'Ändern ✍️',
      'btn_view_map': 'Auf Karte ansehen 🗺️',

      'profile_app_bar_title': 'Partnerprofil & Registrierung',
      'profile_section_title': 'Gastgeber- / Partnerdaten (Obligatorisch)',
      'profile_register_btn_text': 'Partner-Registrierung & Bestätigungs-E-Mail senden',

      'notif_page_title': 'Benachrichtigungseinstellungen',
      'notif_last_minute_title': 'Last-Minute-Angebote',
      'notif_last_minute_desc': 'Benachrichtigen, wenn Blitzangebote verfügbar sind',

      'btn_table_reservation': 'Tisch reservieren 🍽️',
      'btn_call_restaurant': 'Anrufen',
      'label_opening_hours': 'Öffnungszeiten',
      'label_menu_preview': 'Menü & Details',

      'faq_page_title': 'Häufig gestellte Fragen & Funktion 💡',
      'faq_header_title': 'Die zypriotische Erlebnisplattform der Zukunft',
      'faq_header_desc': 'Direkter Kontakt, 0% Provision, verifizierte Unterkünfte und blitzschnelle Last-Minute-Push-Benachrichtigungen.',
      'faq_q1': 'Was ist CYVESTA und wie unterscheidet es sich von einer normalen Website?',
      'faq_a1': 'CYVESTA ist ein exklusives mobiles Ökosystem für ganz Zypern mit nativer Geschwindigkeit, direktem WhatsApp-Kontakt und Live-iCal-Kalendersynchronisation.',
      'faq_q2': 'Wie funktionieren Last-Minute- & Flash-Deal-Push-Benachrichtigungen? ⚡',
      'faq_a2': 'Bei unerwarteten Stornierungen können Gastgeber direkt über die App in 30 Sekunden ein Last-Minute-Angebot an alle Follower senden.',
      'faq_q3': 'Warum lohnt sich CYVESTA mehr als Booking oder Airbnb?',
      'faq_a3': 'Große Plattformen berechnen 15-25% Provision. Bei CYVESTA beträgt die Provision 0%! Sie behalten 100% Ihres Umsatzes.',
      'faq_q4': 'Wie viel kostet die Nutzung der App für Gäste?',
      'faq_a4': 'Für Gäste und Reisende ist die Nutzung von CYVESTA zu 100% KOSTENLOS (0 EUR). Keine Registrierungsgebühren.',
      'faq_q5': 'Wie können Gastgeber, Restaurants und Reiseveranstalter werben?',
      'faq_a5': 'Partner können mit einem günstigen Festbeitrag beitreten: Jahresmitgliedschaft €240 / Jahr (nur €20 / Monat).',
      'faq_q6': 'Wie funktioniert die Live-iCal-Kalendersynchronisation?',
      'faq_a6': 'Gastgeber fügen einfach ihren Airbnb- oder Booking-.ics-Link ein. Doppelbuchungen sind somit komplett ausgeschlossen!',
      'faq_q7': 'Wo sind die offiziellen AGB und DSGVO-Richtlinien zu finden?',
      'faq_a7': 'Die vollständigen Geschäftsbedingungen und Datenschutzbestimmungen können über folgendes Dokument eingesehen werden:',
      'faq_doc_link': '📂 Offizielles AGB & DSGVO Google-Dokument öffnen',
      'faq_footer_title': 'Werden Sie jetzt Partner!',
      'faq_footer_desc': 'Direkte WhatsApp-Buchungen und Last-Minute-Push für nur €20/Monat.',
      'faq_footer_btn': 'Partnerpläne ansehen 💎',
    },

    'ru': {
      'slogan': 'Откройте для себя Кипр: Жилье, Вкусы и Туры',
      'search_region_hint': 'Выберите регион или город...',
      'cat_accommodations': 'Апартаменты\nи Недвижимость',
      'cat_experiences': 'Впечатления\nи Туры',
      'cat_gastronomy': 'Гастрономия\nи Бары',
      'cat_transfer': 'Трансфер\nиз аэропорта ✈️',
      'nearby_search_bar': 'Прокат авто, аптеки, магазины рядом...',
      'nearby_services_title': 'Услуги рядом на карте 🗺️',
      'choose_region_title': 'Выберите направление на Кипре 🏝️',
      'view_details': 'Подробнее',
      'featured_badge': 'РЕКОМЕНДУЕМ',
      'all_regions': 'Все регионы',

      'auth_login_title': 'Вход в CYVESTA',
      'auth_register_title': 'Создать аккаунт',
      'auth_desc': 'Сохраняйте избранное и управляйте бронированиями!',
      'auth_email_hint': 'Эл. почта',
      'auth_password_hint': 'Пароль',
      'auth_name_hint': 'Имя и фамилия',
      'auth_business_name_hint': 'Название компании / Хозяина',
      'auth_tax_hint': 'Реквизиты / ИНН компании',
      'auth_address_hint': 'Адрес (Город, улица, дом)',
      'auth_phone_hint': 'Номер телефона',
      'auth_forgot_pass': 'Забыли пароль?',
      'auth_login_btn': 'Войти',
      'auth_register_btn': 'Регистрация',
      'auth_or_social': 'Или продолжить через:',
      'auth_google': 'Продолжить с Google',
      'auth_apple': 'Продолжить с Apple',
      'auth_facebook': 'Продолжить с Facebook',
      'auth_switch_to_register': 'Нет аккаунта? Зарегистрируйтесь!',
      'auth_switch_to_login': 'Уже есть аккаунт? Войдите!',
      'auth_logout_btn': 'Выйти',
      'auth_logged_in_as': 'Вы вошли как:',
      'auth_btn_main': 'Вход и Профиль 👤',
      'lang_title': 'Выберите язык',

      'terms_acceptance': 'Я принимаю Условия использования и политику конфиденциальности GDPR. *',
      'role_guest': 'Гость',
      'role_free': 'БЕСПЛАТНО',
      'role_annual': 'Годовой партнер ⭐',
      'role_annual_price': '€240 (€20/мес)',
      'role_half_year': 'Партнер на 6 мес.',
      'role_half_year_price': '€180 (6 мес.)',

      'btn_stripe_annual': 'Оплата Stripe и регистрация (€240/год)',
      'btn_stripe_half': 'Оплата Stripe и регистрация (€180/6 мес.)',
      'btn_guest_reg': 'Бесплатная регистрация гостя',

      'transfer_title': 'Трансфер из аэропорта ✈️🚖',
      'transfer_header_title': 'Надежные трансферы на Кипре',
      'transfer_header_desc': 'Трансферы по фиксированной цене из аэропортов Ларнаки и Пафоса.',
      'transfer_step1_title': '1. Направление трансфера',
      'transfer_dir_to_stay': 'Аэропорт ➔ Проживание',
      'transfer_dir_to_airport': 'Проживание ➔ Аэропорт',
      'transfer_step2_title': '2. Детали рейса и пункта назначения',
      'transfer_dest_hint': 'Название жилья / Город',
      'transfer_flight_num': 'Номер рейса (например, W6 2451)',
      'transfer_phone_hint': 'Номер телефона / Контакт WhatsApp *',
      'transfer_submit_btn': 'Запросить расчет трансфера (WhatsApp) 🚖',
      'transfer_fill_required': 'Пожалуйста, введите пункт назначения и контактные данные!',

      'choose_property_type': 'Выберите тип недвижимости 🏠',
      'rent_apartments': 'Апартаменты и Аренда',
      'rent_apartments_desc': 'Долгосрочная или краткосрочная аренда на Кипре.',
      'sale_properties': 'Недвижимость на продажу и Виллы',
      'sale_properties_desc': 'Объекты на первой линии моря и инвестиции.',

      'serv_car_rental': 'Аренда авто',
      'serv_car_rental_desc': 'Арендуйте автомобиль на Кипре',
      'serv_bike_rental': 'Аренда велосипедов',
      'serv_bike_rental_desc': 'Исследуйте пейзажи на двух колесах',
      'serv_pharmacy': 'Аптека',
      'serv_pharmacy_desc': 'Аптеки поблизости',
      'serv_supermarket': 'Супермаркет',
      'serv_supermarket_desc': 'Магазины рядом',
      'serv_nightlife': 'Ночная жизнь',
      'serv_nightlife_desc': 'Бары, клубы и развлечения',
      'serv_bus_stop': 'Остановка автобуса',
      'serv_bus_stop_desc': 'Остановки общественного транспорта',
      'serv_atm': 'Банкомат',
      'serv_atm_desc': 'Точки снятия наличных',
      
      'calendar_free': 'Свободно',
      'calendar_booked': 'Занято',
      'calendar_pending': 'Ожидание',
      'calendar_section_title': 'Календарь бронирования & iCal 📅',
      'details_section_title': 'Описание & Детали 📖',
      'selected_dates_label': 'Выбранные даты:',
      'total_price_label': 'Итого:',
      
      'desc_sale': 'Красивая эксклюзивная недвижимость на первой линии моря на Кипре с премиальными удобствами и частным бассейном.',
      'desc_rent': 'Прекрасное жилье с первоклассным оборудованием и отличным расположением для идеального отдыха на Кипре.',
      'book_table_btn': 'Забронировать столик 🍽️',

      'month_july': 'Июль 2026',
      'day_mo': 'ПН',
      'day_tu': 'ВТ',
      'day_we': 'СР',
      'day_th': 'ЧТ',
      'day_fr': 'ПТ',
      'day_sa': 'СБ',
      'day_su': 'ВС',

      'btn_internal_chat': 'Внутренний чат',
      'btn_select_date': 'Выбрать дату 🗓️',
      'btn_modify': 'Изменить ✍️',
      'btn_view_map': 'Посмотреть на карте 🗺️',

      'profile_app_bar_title': 'Профиль партнера и регистрация',
      'profile_section_title': 'Данные хозяина / партнера (Обязательно)',
      'profile_register_btn_text': 'Регистрация партнера и отправка письма подтверждения',

      'notif_page_title': 'Настройки уведомлений',
      'notif_last_minute_title': 'Горящие предложения',
      'notif_last_minute_desc': 'Уведомлять о появлении спецпредложений',

      'btn_table_reservation': 'Забронировать 🍽️',
      'btn_call_restaurant': 'Позвонить',
      'label_opening_hours': 'Часы работы',
      'label_menu_preview': 'Меню и детали',

      'faq_page_title': 'Часто задаваемые вопросы 💡',
      'faq_header_title': 'Премиальная платформа Кипра',
      'faq_header_desc': 'Прямая связь, 0% комиссия, проверенные объекты и мгновенные Last Minute Push уведомления.',
      'faq_q1': 'Что такое CYVESTA и чем она отличается от обычного сайта?',
      'faq_q2': 'Как работают Push-уведомления о Last Minute скидках? ⚡',
      'faq_q3': 'Почему CYVESTA выгоднее, чем Booking или Airbnb?',
      'faq_q4': 'Сколько стоит использование приложения для гостей?',
      'faq_q5': 'Как владельцы жилья и ресторанов могут разместить рекламу?',
      'faq_q6': 'Как работает синхронизация календаря iCal в реальном времени?',
      'faq_q7': 'Где можно найти официальные Условия и политику конфиденциальности GDPR?',
      'faq_doc_link': '📂 Открыть официальный документ Условий и GDPR',
      'faq_footer_title': 'Станьте партнером CYVESTA!',
      'faq_footer_desc': 'Прямые бронирования WhatsApp и Last Minute Push всего за €20/месяц.',
      'faq_footer_btn': 'Посмотреть планы партнеров 💎',
    },
  };

  static String tr(String key) {
    final lang = currentLocale.value;
    if (_dict.containsKey(lang) && _dict[lang]!.containsKey(key)) {
      return _dict[lang]![key]!;
    }
    if (_dict['en'] != null && _dict['en']!.containsKey(key)) {
      return _dict['en']![key]!;
    }
    if (_dict['hu'] != null && _dict['hu']!.containsKey(key)) {
      return _dict['hu']![key]!;
    }
    return key;
  }
}